eureka:
    client:
        service-url:
            default: http://localhost:8761/eureka
            defaultZone: http://localhost:8761/eureka
server:
    port: 80
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: ResourceService
                  uri: lb://resource-server
                  predicates:
                      - Path=/getUser  #path wiill not be

