##debug: true
##eureka:
##  client:
##    service-url:
##      default: http://localhost:8761/eureka
##      defaultZone: http://localhost:8761/eureka
#server:
#  port: 80
#spring:
#  application:
#    name: api-gateway
#  cloud:
#    config:
#      uri: http://localhost:5000
##    gateway:
##      routes:
##        - id: ResourceService
##          uri: lb://resource-server
##          predicates:
##            - Path=/user/**
#
